{% set data = load_setup_py_data() %}

package:
  name: fip
  version: {{ data.get('version') }}

build:
  noarch: python
  preserve_egg_dir: True

extra:
  channels:
    - rdkit
    - lich

source:
  path: ../

requirements:
  build:
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - rdkit
    - pandas

about:
  home: {{ data.get('url') }}
  license: GPL-3.0
  license_file: LICENSE
  summary:  {{ data.get('description') }}
